<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Bird Song | Biostatistics Portfolio II</title>
  <meta name="description" content="Chapter 1 Bird Song | Biostatistics Portfolio II" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Bird Song | Biostatistics Portfolio II" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Bird Song | Biostatistics Portfolio II" />
  
  
  

<meta name="author" content="Dr. F.J. Rodenburg   © 2021 Leiden University" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostatistics Portfolio II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="bird-song.html"><a href="bird-song.html"><i class="fa fa-check"></i><b>1</b> Bird Song</a><ul>
<li class="chapter" data-level="1.1" data-path="bird-song.html"><a href="bird-song.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="bird-song.html"><a href="bird-song.html#a-complex-experimental-design"><i class="fa fa-check"></i><b>1.2</b> A Complex Experimental Design</a><ul>
<li class="chapter" data-level="1.2.1" data-path="bird-song.html"><a href="bird-song.html#braintransform"><i class="fa fa-check"></i><b>1.2.1</b> The Outcome Is Skewed</a></li>
<li class="chapter" data-level="1.2.2" data-path="bird-song.html"><a href="bird-song.html#braindependence"><i class="fa fa-check"></i><b>1.2.2</b> The Measurements are Dependent</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="bird-song.html"><a href="bird-song.html#analysis-with-a-mixed-model"><i class="fa fa-check"></i><b>1.3</b> Analysis With a Mixed Model</a><ul>
<li class="chapter" data-level="1.3.1" data-path="bird-song.html"><a href="bird-song.html#install-package-lmertest"><i class="fa fa-check"></i><b>1.3.1</b> Install Package <code>lmerTest</code></a></li>
<li class="chapter" data-level="1.3.2" data-path="bird-song.html"><a href="bird-song.html#load-package-lmertest"><i class="fa fa-check"></i><b>1.3.2</b> Load Package <code>lmerTest</code></a></li>
<li class="chapter" data-level="1.3.3" data-path="bird-song.html"><a href="bird-song.html#brainmodel"><i class="fa fa-check"></i><b>1.3.3</b> Fit a Mixed Model With <code>lmer()</code></a></li>
<li class="chapter" data-level="1.3.4" data-path="bird-song.html"><a href="bird-song.html#interpretbrain"><i class="fa fa-check"></i><b>1.3.4</b> Interpreting the Output</a></li>
<li class="chapter" data-level="1.3.5" data-path="bird-song.html"><a href="bird-song.html#simplifying-the-model"><i class="fa fa-check"></i><b>1.3.5</b> Simplifying the model</a></li>
<li class="chapter" data-level="1.3.6" data-path="bird-song.html"><a href="bird-song.html#comparebrain"><i class="fa fa-check"></i><b>1.3.6</b> Decide on the right model</a></li>
<li class="chapter" data-level="1.3.7" data-path="bird-song.html"><a href="bird-song.html#brainoutput"><i class="fa fa-check"></i><b>1.3.7</b> Interpret the final output</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="bird-song.html"><a href="bird-song.html#assignment-data-cleaning"><i class="fa fa-check"></i><b>1.4</b> Assignment: Data Cleaning</a><ul>
<li class="chapter" data-level="1.4.1" data-path="bird-song.html"><a href="bird-song.html#read-the-data-and-look-at-the-structure"><i class="fa fa-check"></i><b>1.4.1</b> Read the data and look at the structure</a></li>
<li class="chapter" data-level="1.4.2" data-path="bird-song.html"><a href="bird-song.html#shorten-variable-names-and-change-variable-types"><i class="fa fa-check"></i><b>1.4.2</b> Shorten variable names and change variable types</a></li>
<li class="chapter" data-level="1.4.3" data-path="bird-song.html"><a href="bird-song.html#fix-errors-in-data-entry"><i class="fa fa-check"></i><b>1.4.3</b> Fix errors in data entry</a></li>
<li class="chapter" data-level="1.4.4" data-path="bird-song.html"><a href="bird-song.html#plot-your-data"><i class="fa fa-check"></i><b>1.4.4</b> Plot your data</a></li>
<li class="chapter" data-level="1.4.5" data-path="bird-song.html"><a href="bird-song.html#inspect-suspicious-values"><i class="fa fa-check"></i><b>1.4.5</b> Inspect suspicious value(s)</a></li>
<li class="chapter" data-level="1.4.6" data-path="bird-song.html"><a href="bird-song.html#remove-unrealistic-values"><i class="fa fa-check"></i><b>1.4.6</b> Remove unrealistic value(s)</a></li>
<li class="chapter" data-level="1.4.7" data-path="bird-song.html"><a href="bird-song.html#remove-values-incorrectly-marked-0"><i class="fa fa-check"></i><b>1.4.7</b> Remove values incorrectly marked “0”</a></li>
<li class="chapter" data-level="1.4.8" data-path="bird-song.html"><a href="bird-song.html#other-changes"><i class="fa fa-check"></i><b>1.4.8</b> Other changes</a></li>
<li class="chapter" data-level="1.4.9" data-path="bird-song.html"><a href="bird-song.html#run-the-analysis"><i class="fa fa-check"></i><b>1.4.9</b> Run the analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Biostatistics Portfolio II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bird-song" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Bird Song</h1>
<p><small><i>In this chapter, an advanced analysis is shown of the volume of different areas of the bird brain related to song. Your assignment is to read the explanation, have a look at the analysis used, and then perform <strong>data cleaning</strong> on your own data. Once your data is ready, copy the analysis and write a conclusion.</i></small></p>
<hr />
<div id="introduction" class="section level2">
<h2><span class="header-section-number">1.1</span> Introduction</h2>
<p>Statistical analysis is about explaining the different sources of variance. A source of variance can be of interest, like the different areas of the brain, but it can also simply be a source of potential errors, like which student is performing the measurements, or which particular bird you are measuring. By correctly accounting for the different sources of variance, we end up with a powerful model that gives trustworthy standard errors and <span class="math inline">\(p\)</span>-values.</p>
<p>In this analysis I want to demonstrate three things:</p>
<ol style="list-style-type: decimal">
<li><strong>A complicated experimental design</strong> like this one requires a complicated model called a mixed model;</li>
<li><strong>Comparing the groups with a mixed model</strong> can fortunately still be fairly easy to do in R, and its results match up with the expectations.</li>
<li><strong>Data cleaning</strong> is part of every analysis, and has a great impact on the results. This is the part you will be doing by yourself. The analysis you can then copy from my example.</li>
</ol>
<p>This chapter will demonstrate how (1) study design is a crucial part of scientific research, which dictates the type of model you should use; (2) even if you do not fully understand the (statistical) methods used in papers, you can still judge the validity of one’s approach, and read the results; (3) even simple data cleaning can be a time-consuming task that requires careful consideration of how the data came to be.</p>
<p>Throughout this chapter I will use example data from a different year. You data should be (more or less) the same. Any differences you can iron out in the data cleaning assignment.</p>
</div>
<div id="a-complex-experimental-design" class="section level2">
<h2><span class="header-section-number">1.2</span> A Complex Experimental Design</h2>
<p>The experiment consisted of measuring the total volume of different parts of the brain related to song. This experimental design has two difficulties that I want to address, before showing which model I used. Hopefully that will make it clear <em>why</em> I used the model shown in the next paragraph, even if you are not familiar with it.</p>
<div id="braintransform" class="section level3">
<h3><span class="header-section-number">1.2.1</span> The Outcome Is Skewed</h3>
<p>If a distribution has more deviations in one direction than the other, we call it <a href="https://en.wikipedia.org/wiki/Skewness">skewed</a>:</p>
<p><img src="Biostatistics_files/figure-html/skewedbrain-1.png" width="672" /></p>
<p>This histogram of the volume displays strong right-skew: Volumes of <span class="math inline">\(0\)</span>–<span class="math inline">\(0.2\)</span> are most common, <span class="math inline">\(0.2\)</span>–<span class="math inline">\(0.4\)</span> less common, and any larger volumes are exceedingly rare.</p>
<p>The model we’re going to use in the next paragraph assumes (like many statistical tests and models) that if we account for the effects of the explanatory variables, what remains should be more or less <a href="https://www.mathsisfun.com/data/standard-normal-distribution.html">normally distributed</a> noise. With a response variable this strongly skewed, it is unlikely that assumption will hold. Even if we split by area of the brain, the distribution of volume is still right-skewed:</p>
<p><img src="Biostatistics_files/figure-html/marginalbrain-1.png" width="672" /></p>
<p>Why is volume so strongly right-skewed? Because the volume grows cubically (<span class="math inline">\(x^3\)</span>): Volume is a three-dimensional measurement, determined by the length, width and depth. Therefore, we could consider <em>transforming</em> the outcome as follows:</p>
<p><img src="Biostatistics_files/figure-html/unskewedbrain-1.png" width="672" /></p>
<p>We can also split by area again and see that there is indeed no more right-skew:</p>
<p><img src="Biostatistics_files/figure-html/marginalunskewedbrain-1.png" width="672" /></p>
</div>
<div id="braindependence" class="section level3">
<h3><span class="header-section-number">1.2.2</span> The Measurements are Dependent</h3>
<div class="figure"><span id="fig:crossedrandomfig"></span>
<img src="Biostatistics_files/figure-html/crossedrandomfig-1.png" alt="\label{fig:crossedrandom}A simplified version of the experiment. Each bird has had different parts of its brain measured by different students." width="672" />
<p class="caption">
Figure 1.1: A simplified version of the experiment. Each bird has had different parts of its brain measured by different students.
</p>
</div>
<p>Here is a very brief description of <font color = "#3979A8"><strong>the problem</strong></font> and <font color = "#DB4639"><strong>the solution</strong></font>:</p>
<ul>
<li><font color = "#3979A8"><strong>Most tests and models assume independent measurements</strong></font>;</li>
<li>Each bird in the data set has been measured more than once (different brain areas). These measurements come from the same individual and are therefore, <font color = "#3979A8"><strong>measurements of the same bird are not independent</strong></font>;</li>
<li>In the first year’s course about statistics you learned to <font color = "#DB4639"><strong>compare dependent data</strong></font> through a paired <span class="math inline">\(t\)</span>-test. A paired <span class="math inline">\(t\)</span>-test can only compare two sets of paired measurements;</li>
<li>A more general way to deal with dependent data is <font color = "#DB4639"><strong>through a mixed model</strong></font>.</li>
<li>This works <font color = "#DB4639"><strong>by estimating a random effect for birds</strong></font>. This is like assuming that these birds come from some larger population of birds we could have used in the experiment. Instead of estimating a separate effect for each bird, we estimate the variance between birds and subtract the effect of the individual birds from the effects of interest.</li>
</ul>
<p>Another potential source of dependence is… you! No matter how hard we try to perform measurements according to protocol, there will always be minor, but systematic differences in the way each student performs the measurement. If each student performed one measurement, this would not pose any problem. However, as shown in figure , each student has performed several measurements. If the differences in measurement between students are sufficiently large, this poses a problem. Therefore, <font color = "#3979A8"><strong>measurements of the same student might be correlated</strong></font>.</p>
<p>Fortunately, both problems can be tackled with the same solution: A <font color = "#DB4639"><strong>mixed model</strong></font>.</p>
</div>
</div>
<div id="analysis-with-a-mixed-model" class="section level2">
<h2><span class="header-section-number">1.3</span> Analysis With a Mixed Model</h2>
<p>To fit a mixed model, we are going to use a package called <code>lmerTest</code>. The entire procedure then boils down to:</p>
<ol style="list-style-type: decimal">
<li>Install package <code>lmerTest</code> if you don’t have it;</li>
<li>Load package <code>lmerTest</code>;</li>
<li>Fit a mixed model with <code>lmer()</code>;
<ul>
<li>Use <a href="bird-song.html#braintransform">the transformation described above</a>;</li>
<li>Specify <a href="bird-song.html#braindependence">which variables cause the dependence</a>.</li>
</ul></li>
</ol>
<div id="install-package-lmertest" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Install Package <code>lmerTest</code></h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="bird-song.html#cb1-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;lmerTest&quot;</span>)</span></code></pre></div>
</div>
<div id="load-package-lmertest" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Load Package <code>lmerTest</code></h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="bird-song.html#cb2-1"></a><span class="kw">library</span>(<span class="st">&quot;lmerTest&quot;</span>)</span></code></pre></div>
</div>
<div id="brainmodel" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Fit a Mixed Model With <code>lmer()</code></h3>
<p>Let’s call this model <code>model1</code>:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="bird-song.html#cb3-1"></a>model1 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Area <span class="op">+</span><span class="st"> </span>Hemisphere <span class="op">+</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>BirdID) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>StudentID), <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<ul>
<li><code>lmer</code> is short for linear mixed effects regression—a mixed model;</li>
<li><code>Volume</code> is transformed as <span class="math inline">\(\sqrt[3]{x} = x^{\frac{1}{3}}\)</span> <a href="bird-song.html#braintransform">as explained earlier</a>;</li>
<li><code>Area</code> and <code>Hemisphere</code> are the effects of interest;</li>
<li>Using the <code>(1 | ...)</code> notation, I am telling the function I want to estimate the variance between birds and the variance between students;</li>
<li>Using the <code>data</code> argument, I am telling the function where to find all these variables.</li>
</ul>
<p>That’s the whole model! You might not have been able to think of that yourself, but if you understand why this particular model was used, that is more than enough.</p>
</div>
<div id="interpretbrain" class="section level3">
<h3><span class="header-section-number">1.3.4</span> Interpreting the Output</h3>
<p>Let’s start by producing a summary of the model:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="bird-song.html#cb4-1"></a><span class="kw">summary</span>(model1)</span></code></pre></div>
<p>There’s a lot going on in the summary, and most of it is not relevant for this assignment. Therefore, the only thing I’ve show here is the <code>Random effects</code> and <code>Fixed effects</code> tabs.</p>
<pre><code>Random effects:
 Groups    Name        Variance  Std.Dev.
 StudentID (Intercept) 0.0006164 0.02483 
 BirdID    (Intercept) 0.0053421 0.07309 
 Residual              0.0064676 0.08042 
Number of obs: 318, groups:  StudentID, 75; BirdID, 32

Fixed effects:
              Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept)   0.595091   0.034643 36.805541  17.178  &lt; 2e-16 ***
AreaHVC      -0.211419   0.014083 62.855150 -15.012  &lt; 2e-16 ***
AreaRA       -0.261225   0.014406 61.958464 -18.134  &lt; 2e-16 ***
HemisphereR   0.003952   0.010848 46.077031   0.364  0.71732    
TreatmentF5  -0.039343   0.045208 26.549452  -0.870  0.39196    
TreatmentF15  0.109993   0.043607 26.671033   2.522  0.01794 *  
TreatmentF50  0.168776   0.045011 26.117294   3.750  0.00089 ***
TreatmentM0   0.364359   0.043560 26.567674   8.365 6.41e-09 ***</code></pre>
<p>Here we see that:</p>
<ul>
<li>Variance between students is very small (<code>0.0064676</code>);</li>
<li>Variance between birds is comparable to the residual variance (<code>0.0053421</code> and <code>0.0064676</code>, respectively);</li>
<li>The reference group (Area <code>RA</code>, Hemisphere <code>L</code>, Treatment <code>F0</code>) has a <span class="math inline">\(\sqrt[3]{\text{volume}}\)</span> of <code>0.595091</code>;</li>
<li>The HVC area has lower volume on average (<code>-0.211419</code> lower than <code>RA</code>);</li>
<li>The RA area has yet lower volume on average (<code>-0.261225</code> lower than <code>RA</code>);</li>
<li>The right hemisphere does not differ significantly from the left (difference of <code>0.003952</code>, <span class="math inline">\(p\)</span>-value of <code>0.71732</code>);</li>
<li>Treatment <code>F5</code> does not differ significantly from <code>F0</code> (difference of <code>-0.039343</code>, <span class="math inline">\(p\)</span>-value of <code>0.39196</code>);</li>
<li>Treatment <code>F15</code> has a higher volume than <code>F0</code> on average;</li>
<li>Treatment <code>F50</code> has an even higher volume than <code>F0</code> on average;</li>
<li>Males (<code>M0</code>) have yet higher volume than <code>F0</code> on average.</li>
</ul>
</div>
<div id="simplifying-the-model" class="section level3">
<h3><span class="header-section-number">1.3.5</span> Simplifying the model</h3>
<p>So the variance between students is extremely small. This is actually good news, because it means that the measurements do not depend much at all on who is measuring. If this is also the case in your year’s data, it means your class measured consistently. Good job!</p>
<p>If the effect is so small, you could opt to leave out the random effect for students:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="bird-song.html#cb6-1"></a>model2 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Area <span class="op">+</span><span class="st"> </span>Hemisphere <span class="op">+</span><span class="st"> </span>Treatment <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>BirdID), <span class="dt">data =</span> Birdsong)</span></code></pre></div>
</div>
<div id="comparebrain" class="section level3">
<h3><span class="header-section-number">1.3.6</span> Decide on the right model</h3>
<p>Lastly, we use a test to decide which of these models fits the data better:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="bird-song.html#cb7-1"></a><span class="kw">anova</span>(model1, model2)                                                           </span></code></pre></div>
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>Data: Birdsong
Models:
model2: Volume^(1/3) ~ Area + Hemisphere + Treatment + (1 | BirdID)
model1: Volume^(1/3) ~ Area + Hemisphere + Treatment + (1 | BirdID) + 
model1:     (1 | StudentID)
       npar     AIC     BIC logLik deviance  Chisq Df Pr(&gt;Chisq)
model2   10 -594.34 -556.72 307.17  -614.34                     
model1   11 -594.07 -552.69 308.04  -616.07 1.7325  1     0.1881</code></pre>
<p>First we are notified that the models were refitted using maximum likelihood. This is because measures like AIC, BIC and deviance cannot be calculated from <em>restricted</em> maximum likelihood (the usual fitting procedure for mixed models). In this table we see several things:</p>
<ul>
<li><code>model2</code> uses <span class="math inline">\(10\)</span> parameters, while <code>model1</code> uses <span class="math inline">\(11\)</span>;</li>
<li><code>model2</code> has a lower AIC (note the minus sign);</li>
<li><code>model2</code> has a lower BIC;</li>
<li><code>model2</code> has a marginally lower log-likelihood;</li>
<li><code>model2</code> has a marginally higher remaining deviance (again, note the minus sign);</li>
<li>A chi-squared test on these two values of the deviance produces <span class="math inline">\(\chi^2 = 1.7325\)</span>;</li>
<li>This test has one degree of freedom (the difference in the number of parameters used by the models);</li>
<li>The corresponding <span class="math inline">\(p\)</span>-value for this <span class="math inline">\(\chi^2\)</span>-test on one degree of freedom is <span class="math inline">\(p = 0.1881\)</span>;</li>
<li>This is not significant at any reasonable level of significance;</li>
</ul>
<p>That’s a lot to consider at once, and most of these terms you have probably never heard of before. Fortunately, the relevant part is the easiest to interpret: Neither model fits the data significantly better than the other (<span class="math inline">\(p = 0.1881\)</span>).</p>
<p>The usual thing to do in a situation like this is to go with the model that uses fewer parameters. After all, if you can fit the data just as well with a simpler model, what is the benefit of making it more complex?</p>
</div>
<div id="brainoutput" class="section level3">
<h3><span class="header-section-number">1.3.7</span> Interpret the final output</h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="bird-song.html#cb10-1"></a><span class="kw">summary</span>(model2)</span></code></pre></div>
<pre><code>Random effects:
 Groups   Name        Variance Std.Dev.
 BirdID   (Intercept) 0.005537 0.07441 
 Residual             0.007019 0.08378 
Number of obs: 318, groups:  BirdID, 32

Fixed effects:
               Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)    0.591845   0.034869  36.260578  16.974  &lt; 2e-16 ***
AreaHVC       -0.208483   0.012627 285.552762 -16.511  &lt; 2e-16 ***
AreaRA        -0.257411   0.012897 286.979684 -19.959  &lt; 2e-16 ***
HemisphereR    0.003086   0.009461 284.170394   0.326 0.744541    
TreatmentF5   -0.039735   0.046147  27.947606  -0.861 0.396535    
TreatmentF15   0.110134   0.044503  28.051566   2.475 0.019642 *  
TreatmentF50   0.170132   0.045926  27.433116   3.705 0.000944 ***
TreatmentM0    0.365201   0.044446  27.916048   8.217 6.21e-09 ***</code></pre>
<p>Here we see that the individual difference between birds is actually quite large: Its variance of <code>0.005537</code> is almost the same as the remaining variance after accounting for all effects of <code>0.007019</code>.</p>
<p>We also see that the estimated effects and their significance differs very little from <a href="bird-song.html#interpretbrain">the previous output of <code>model1</code></a>. This is desirable, because if the difference in estimates were very large, we would have to put more thought into which model we believe to be the right one. In this case, either model gives more or less the same answer to the research question.</p>
<p>Moreover, as you’ll see in the assignment, the results match up nicely with what you see in the boxplots.</p>
</div>
</div>
<div id="assignment-data-cleaning" class="section level2">
<h2><span class="header-section-number">1.4</span> Assignment: Data Cleaning</h2>
<p>So far, I have only covered the experimental design and the model used. But I left out an important part of analysis: Data cleaning.</p>
<p>In the example data above, there were simple errors in the data entry, a problematic outlier, and low quality data mislabeled as <span class="math inline">\(0\)</span>. Here I am going to show how you can clean your data set to make it ready for analysis.</p>
<p><strong>Your assignment</strong> is to clean your own data set following the example here. When you’re done, copy the analysis shown above and write a conclusion.</p>
<div id="read-the-data-and-look-at-the-structure" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Read the data and look at the structure</h3>
<iframe src="https://www.youtube.com/embed/BGUqZc-Pb8w" width="672" height="400px">
</iframe>
<ol style="list-style-type: decimal">
<li>If you haven’t already, <a href="https://fransrodenburg.github.io/Biostatistics-Portfolio-I/installation.html">install RStudio</a>;</li>
<li>Download the data. If it is an Excel (.xlsx) file, open it in Excel and save as comma-separated values (.csv) first;</li>
<li>Open RStudio and <a href="https://youtu.be/2Sovzf6lVRo?t=280">create a new R markdown file</a>. <strong>Save this file to the same folder as the data!</strong></li>
<li>Go to <strong>Session</strong> &gt; <strong>Set Working Directory</strong> &gt; <strong>To Source File Location</strong>. R now knows where to look for your data;</li>
<li><a href="https://youtu.be/AHAR7j-IUOw?t=357">Create a new code chunk</a> and run the following code (<strong>replace the file name</strong> with your file name):</li>
</ol>
<pre><code>## &#39;data.frame&#39;:    376 obs. of  6 variables:
##  $ Student_ID   : int  42 42 42 42 42 73 73 73 73 73 ...
##  $ Zanggebied   : chr  &quot;RA&quot; &quot;RA&quot; &quot;RA&quot; &quot;RA&quot; ...
##  $ Hemisfeer    : chr  &quot;R&quot; &quot;R&quot; &quot;R&quot; &quot;R&quot; ...
##  $ Vogel_ID     : chr  &quot;OG164&quot; &quot;PK179&quot; &quot;PK190&quot; &quot;PK198&quot; ...
##  $ Totaal_volume: num  0.1104 0.0276 0.2304 0.0204 0.3012 ...
##  $ Treatment    : chr  &quot;NA&quot; &quot;F0&quot; &quot;F50&quot; &quot;F5&quot; ...</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="bird-song.html#cb13-1"></a>Birdsong &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Birdsong2020.csv&quot;</span>)</span>
<span id="cb13-2"><a href="bird-song.html#cb13-2"></a><span class="kw">str</span>(Birdsong)</span></code></pre></div>
<p>I will go over the data cleaning of the 2020 data. You can follow along with the data from your own year.</p>
<p>Here we see the following:</p>
<ul>
<li>The data is stored as a <code>data.frame</code>, and consists of 376 observations of 5 variables;</li>
<li>Those variables are:
<ul>
<li><code>Student_ID</code>: An integer value (whole number);</li>
<li><code>Zanggebied</code>: A character value;</li>
<li><code>Hemisfeer</code>: A character value;</li>
<li><code>Vogel_ID</code>: A character value;</li>
<li><code>Totaal_volume</code>: A numeric value (any number);</li>
<li><code>Treatment</code>: A character value.</li>
</ul></li>
</ul>
</div>
<div id="shorten-variable-names-and-change-variable-types" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Shorten variable names and change variable types</h3>
<p>The first step I made is change the variable names to be slightly shorter (and in English) and convert the categorical variables to factors:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="bird-song.html#cb14-1"></a><span class="kw">colnames</span>(Birdsong)  &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;StudentID&quot;</span>, <span class="st">&quot;Area&quot;</span>, <span class="st">&quot;Hemisphere&quot;</span>, <span class="st">&quot;BirdID&quot;</span>, <span class="st">&quot;Volume&quot;</span>, <span class="st">&quot;Treatment&quot;</span>)</span>
<span id="cb14-2"><a href="bird-song.html#cb14-2"></a>Birdsong<span class="op">$</span>StudentID  &lt;-<span class="st"> </span><span class="kw">factor</span>(Birdsong<span class="op">$</span>StudentID)</span>
<span id="cb14-3"><a href="bird-song.html#cb14-3"></a>Birdsong<span class="op">$</span>Area       &lt;-<span class="st"> </span><span class="kw">factor</span>(Birdsong<span class="op">$</span>Area)</span>
<span id="cb14-4"><a href="bird-song.html#cb14-4"></a>Birdsong<span class="op">$</span>Hemisphere &lt;-<span class="st"> </span><span class="kw">factor</span>(Birdsong<span class="op">$</span>Hemisphere)</span>
<span id="cb14-5"><a href="bird-song.html#cb14-5"></a>Birdsong<span class="op">$</span>BirdID     &lt;-<span class="st"> </span><span class="kw">factor</span>(Birdsong<span class="op">$</span>BirdID)</span>
<span id="cb14-6"><a href="bird-song.html#cb14-6"></a>Birdsong<span class="op">$</span>Treatment  &lt;-<span class="st"> </span><span class="kw">factor</span>(Birdsong<span class="op">$</span>Treatment, </span>
<span id="cb14-7"><a href="bird-song.html#cb14-7"></a>                              <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;F0&quot;</span>, <span class="st">&quot;F5&quot;</span>, <span class="st">&quot;F15&quot;</span>, <span class="st">&quot;F50&quot;</span>, <span class="st">&quot;M0&quot;</span>))</span></code></pre></div>
<p>Why does that matter? Well, have a look what happens when you check the structure again:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="bird-song.html#cb15-1"></a><span class="kw">str</span>(Birdsong)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    376 obs. of  6 variables:
##  $ StudentID : Factor w/ 75 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 38 38 38 38 38 65 65 65 65 65 ...
##  $ Area      : Factor w/ 5 levels &quot;Area X&quot;,&quot;HCV&quot;,..: 5 5 5 5 5 1 1 1 1 1 ...
##  $ Hemisphere: Factor w/ 2 levels &quot;L&quot;,&quot;R&quot;: 2 2 2 2 2 1 1 1 1 1 ...
##  $ BirdID    : Factor w/ 69 levels &quot;Bk 145&quot;,&quot;BK 145&quot;,..: 38 59 60 61 68 64 19 49 51 50 ...
##  $ Volume    : num  0.1104 0.0276 0.2304 0.0204 0.3012 ...
##  $ Treatment : Factor w/ 5 levels &quot;F0&quot;,&quot;F5&quot;,&quot;F15&quot;,..: NA 1 4 2 5 5 3 1 2 4 ...</code></pre>
<p>Now we see that there were apparently 75 students, and… wait, <em>5</em> areas?</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="bird-song.html#cb17-1"></a><span class="kw">summary</span>(Birdsong<span class="op">$</span>Area)</span></code></pre></div>
<pre><code>## Area X    HCV    HVC     Ra     RA 
##    125      5    128      1    117</code></pre>
<p>Ah, some people entered <code>Ra</code> instead of <code>RA</code>, and some entered <code>HCV</code> instead of <code>HVC</code>. Let’s fix their mistakes:</p>
</div>
<div id="fix-errors-in-data-entry" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Fix errors in data entry</h3>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="bird-song.html#cb19-1"></a>Birdsong<span class="op">$</span>Area[Birdsong<span class="op">$</span>Area <span class="op">==</span><span class="st"> &quot;Ra&quot;</span>]  &lt;-<span class="st"> &quot;RA&quot;</span></span>
<span id="cb19-2"><a href="bird-song.html#cb19-2"></a>Birdsong<span class="op">$</span>Area[Birdsong<span class="op">$</span>Area <span class="op">==</span><span class="st"> &quot;HCV&quot;</span>] &lt;-<span class="st"> &quot;HVC&quot;</span></span>
<span id="cb19-3"><a href="bird-song.html#cb19-3"></a>Birdsong<span class="op">$</span>Area &lt;-<span class="st"> </span><span class="kw">droplevels</span>(Birdsong<span class="op">$</span>Area)</span></code></pre></div>
<p>The first two lines correct the wrong entries, and the third line removes the now unused levels <code>Ra</code> and <code>HCV</code>.</p>
</div>
<div id="plot-your-data" class="section level3">
<h3><span class="header-section-number">1.4.4</span> Plot your data</h3>
<p>And now we’re good to go! The first thing you should do in any analysis after reading the data is to try and create one or several relevant plots of your data. No amount of looking at numbers is going to give you the same, easy insight as a figure:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="bird-song.html#cb20-1"></a><span class="kw">boxplot</span>(Volume <span class="op">~</span><span class="st"> </span>Hemisphere <span class="op">*</span><span class="st"> </span>Area, <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/plot-1.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="bird-song.html#cb21-1"></a><span class="kw">boxplot</span>(Volume <span class="op">~</span><span class="st"> </span>Treatment, <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/plot-2.png" width="672" /></p>
<p>We can already make several useful observations:</p>
<ul>
<li>Area X seems to have a larger mean<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> and variance<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> than the rest;</li>
<li>The left and right hemispheres do not seem to differ much;</li>
<li>Volume seems to increase from <code>F0</code> to <code>F5</code>, to <code>F15</code> to <code>F50</code>, and males have even larger volume;</li>
<li>There is a suspiciously large value for area X of the right hemisphere (first figure). Is this an unrealistic value?</li>
</ul>
</div>
<div id="inspect-suspicious-values" class="section level3">
<h3><span class="header-section-number">1.4.5</span> Inspect suspicious value(s)</h3>
<p>Let’s inspect the suspicious value further. Since it is the largest value, I can use <code>which.max</code> to find it:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="bird-song.html#cb22-1"></a>suspicious &lt;-<span class="st"> </span><span class="kw">which.max</span>(Birdsong<span class="op">$</span>Volume)</span>
<span id="cb22-2"><a href="bird-song.html#cb22-2"></a>Birdsong<span class="op">$</span>Volume[suspicious] <span class="op">/</span><span class="st"> </span><span class="kw">mean</span>(Birdsong<span class="op">$</span>Volume)</span></code></pre></div>
<pre><code>## [1] 53.86181</code></pre>
<p>This value is <span class="math inline">\(53.9 \times\)</span> larger than the mean total volume. Keep in mind that volume is a three-dimensional measurement. It grows at a rate of <span class="math inline">\(x^3\)</span> with the length, width and depth of the brain. Therefore, at least some extreme observations are expected… So let’s use a transformation that accounts for this:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="bird-song.html#cb24-1"></a><span class="kw">boxplot</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Hemisphere <span class="op">*</span><span class="st"> </span>Area, <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Even with a transformation of <span class="math inline">\(\text{volume}^\frac{1}{3}\)</span>, the suspiciously large value still sticks out quite a lot.</p>
</div>
<div id="remove-unrealistic-values" class="section level3">
<h3><span class="header-section-number">1.4.6</span> Remove unrealistic value(s)</h3>
<p>It is hard to say what this value is supposed to be. It could have been a misplaced decimal separator, but should it then be <span class="math inline">\(1.4292\)</span>, or <span class="math inline">\(0.14292\)</span>? Since we cannot say for sure what it should have been, let’s omit this observation from further analysis:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="bird-song.html#cb25-1"></a>Birdsong &lt;-<span class="st"> </span>Birdsong[<span class="op">-</span>suspicious, ]</span></code></pre></div>
<p>If this analysis were to be used in a publication, we would have to go further: How much does this observation affect the results? Can we use a form of multiple imputation to fill in the missing value we have now created? But for now we’ll leave it at this.</p>
<p>Let’s create the boxplots again to see what the data look like without the suspicious value:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="bird-song.html#cb26-1"></a><span class="kw">boxplot</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Hemisphere <span class="op">*</span><span class="st"> </span>Area, <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>This looks far more reasonable. Now let’s address the next elephant in the room: There appears to be far greater variance in the volume of area X, than in RA or HVC. But notice how measurements of zero almost exclusively occur in area X. We can confirm this as follows:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="bird-song.html#cb27-1"></a><span class="kw">by</span>(Birdsong, Birdsong<span class="op">$</span>Area, <span class="cf">function</span>(x){<span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)})</span></code></pre></div>
<pre><code>## Birdsong$Area: Area X
## [1] 45
## ------------------------------------------------------------ 
## Birdsong$Area: HVC
## [1] 8
## ------------------------------------------------------------ 
## Birdsong$Area: RA
## [1] 0</code></pre>
<p>How do we deal with this? There are several ways to do so, and the best way depends on the problem being studied, as well as the reason for measurements being <span class="math inline">\(0\)</span>. We could, for example, consider these zeroes to be ‘censored’, meaning that they are not actually zero, but just too small to be picked up by the measurement. These kinds of considerations are what make statistical modeling difficult.</p>
</div>
<div id="remove-values-incorrectly-marked-0" class="section level3">
<h3><span class="header-section-number">1.4.7</span> Remove values incorrectly marked “0”</h3>
<p>Fortunately, the cause of the zeroes was in most cases simply a low quality sample, unrelated to the actual volume. It is still suspicious that this happened considerably more often in area X than elsewhere, but for the purpose of this exercise let’s consider these measurements to be missing completely at random. Whatever they were, they weren’t <span class="math inline">\(0\)</span>, and this is skewing the results strongly otherwise.</p>
<p>Therefore, in the next step we set these values to ‘not available’ (<code>NA</code>):</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="bird-song.html#cb29-1"></a>Birdsong<span class="op">$</span>Volume[Birdsong<span class="op">$</span>Volume <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></span></code></pre></div>
<p>One final time we inspect the boxplots:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="bird-song.html#cb30-1"></a><span class="kw">boxplot</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Hemisphere <span class="op">*</span><span class="st"> </span>Area, <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<p><img src="Biostatistics_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>And now we have a fairly good idea of what we should expect in the results: HVC is lower than area X, and RA is even lower. The difference between hemispheres is extremely small and unlikely to be picked up by the model.</p>
</div>
<div id="other-changes" class="section level3">
<h3><span class="header-section-number">1.4.8</span> Other changes</h3>
<p>Are there any other strange values, incorrect labels, or other problems in your version of the data set? Adjust the data in R as you see fit before moving on to the analysis.</p>
</div>
<div id="run-the-analysis" class="section level3">
<h3><span class="header-section-number">1.4.9</span> Run the analysis</h3>
<p>Once you’re over here, you can copy the models I’ve <a href="bird-song.html#brainmodel">shown above</a>:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="bird-song.html#cb31-1"></a>model1 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Area <span class="op">+</span><span class="st"> </span>Hemisphere <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>BirdID) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>StudentID), </span>
<span id="cb31-2"><a href="bird-song.html#cb31-2"></a>               <span class="dt">data =</span> Birdsong)</span>
<span id="cb31-3"><a href="bird-song.html#cb31-3"></a>model2 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Volume<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">~</span><span class="st"> </span>Area <span class="op">+</span><span class="st"> </span>Hemisphere <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>BirdID), </span>
<span id="cb31-4"><a href="bird-song.html#cb31-4"></a>               <span class="dt">data =</span> Birdsong)</span></code></pre></div>
<p>Do both models run without errors? Can you <a href="bird-song.html#comparebrain">compare the models like shown before</a>? What do you conclude from <a href="bird-song.html#brainoutput">the output</a>?</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>If the mean is larger, the location of the boxplot is higher.<a href="bird-song.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>If the variance is larger, the size of the boxplot is larger.<a href="bird-song.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Biostatistics.pdf", "Biostatistics.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
